repos:
  ## system
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: debug-statements
      - id: mixed-line-ending
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort
        types: [python]

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        name: black
        types: [python]

  - repo: https://github.com/flakeheaven/flakeheaven
    rev: 3.2.1
    hooks:
      - id: flakeheaven
        name: flakeheaven
        args: [--config=pyproject.toml]
        additional_dependencies:
          - bandit==1.7.4
          - flake8-bugbear==22.10.27
          - flake8-bandit==3.0.0
          - flake8-builtins==2.0.1
          - flake8-eradicate==1.4.0
          - flake8-mutable==1.2.0
          - pylint==2.15.7
